# Generated by Django 6.0.2 on 2026-02-13 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(unique=True, verbose_name='订阅源地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('fetch_interval', models.IntegerField(default=60, verbose_name='抓取间隔（分钟）')),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True, verbose_name='最后抓取时间')),
                ('last_fetch_status', models.CharField(blank=True, max_length=50, verbose_name='最后抓取状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='core.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '订阅源',
                'verbose_name_plural': '订阅源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_read', models.BooleanField(default=False, verbose_name='自动标记已读')),
                ('show_full_content', models.BooleanField(default=False, verbose_name='显示完整内容')),
                ('items_per_page', models.IntegerField(default=20, verbose_name='每页显示数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='默认分类')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rss_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('url', models.URLField(verbose_name='文章链接')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.feed', verbose_name='订阅源')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['-pub_date'], name='core_articl_pub_dat_1d31fd_idx'), models.Index(fields=['is_read'], name='core_articl_is_read_3543d5_idx'), models.Index(fields=['feed', '-pub_date'], name='core_articl_feed_id_0d3b6b_idx')],
            },
        ),
    ]
