# Generated by Django 6.0.2 on 2026-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='last_auto_fetch_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后自动刷新时间'),
        ),
    ]
